### ISSUE TITLE
The given link does not work for me

### ISSUE THREAD

**Issue by AndyTheBoss** [MunyDev/skiovox-breakout#5]
This is what it says:

URL:  filesystem:chrome-extension://haldlgldplgnggkjaafhelgiaglafanh/temporary/shim.html

Page:

Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

**Comment by MunyDev** [comment]
type this in and then press alt-shift-enter filesystem:chrome-extension://haldlgldplgnggkjaafhelgiaglafanh/temporary/shim.html
